# Generated by Django 4.2 on 2023-05-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=400)),
                ('duedate', models.DateField()),
                ('complete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'todotask',
            },
        ),
    ]
